server:
  port: 8080
  servlet:
    context-path: /vietvivu

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true


  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          max-completion-tokens: 2048
          temperature: 1.0
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      pgvector:
        table-name: tour_vectors     # tên bảng chứa vector
        dimensions: 1536          # số chiều vector (phải đúng với model embedding)
        distance-type: cosine_distance
        index-type: none
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  main:
    allow-bean-definition-overriding: true

outbound:
  identity:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect_uri: ${REDIRECT_URI}

jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

payos:
  client-id: ${CLIENT_ID_PAYOS}
  api-key: ${API_KEY}
  checksum-key: ${CHECKSUM_KEY}