server:
  port: 8080
  servlet:
    context-path: /vietvivu

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: admin
#    password: admin
#    virtual-host: /
  main:
    allow-bean-definition-overriding: true

outbound:
  identity:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect_uri: ${REDIRECT_URI}

jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

# Nếu muốn kiểm tra queue mặc định
app:
  queue:
    name: bookingQueue
