server:
  port: 8080
  servlet:
    context-path: /vietvivu

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true

  # --- CẤU HÌNH MAIL (MỚI THÊM) ---
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # --------------------------------

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          max-completion-tokens: 2048
          temperature: 1.0
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      pgvector:
        table-name: tour_vectors
        dimensions: 1536
        distance-type: cosine_distance
        index-type: none
  main:
    allow-bean-definition-overriding: true

outbound:
  identity:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect_uri: ${REDIRECT_URI}

jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 3600
  refreshable-duration: 36000

payos:
  client-id: ${CLIENT_ID_PAYOS}
  api-key: ${API_KEY}
  checksum-key: ${CHECKSUM_KEY}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

# --- EMAIL BAN TƯ VẤN (MỚI THÊM) ---
app:
  consulting-email: ${CONSULTING_EMAIL}
# -----------------------------------